name: FL data preperation

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'fedlearn' 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Provision resources
      run: |
        clients=( europe asia us)
        export KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}
        export KAGGLE_KEY=${{ secrets.KAGGLE_PASSWORD }}

        az configure --defaults group="${{ github.event.inputs.resource_group }}"

        # Download the Pneumonia dataset
        pip install kaggle
        pip install split-folders
        kaggle datasets download -d jtiptj/chest-xray-pneumoniacovid19tuberculosis -p /tmp
        unzip -q /tmp/chest-xray-pneumoniacovid19tuberculosis.zip -d /tmp

        # split in train, val and test
        splitfolders --output /tmp/chest_xray_new/ --ratio .8 .1 .1 --seed 33 --move -- /tmp/train

        # store central dataset to asia hospital
        az ml data create --workspace-name Asia-Hospital3 \
                          --name pneumonia-central3 \
                          --path /tmp/chest_xray_new \
                          --type uri_folder

        stages=( train test val )
        classes=(COVID19 NORMAL PNEUMONIA TURBERCULOSIS)

        # Create folders
        for client in "${clients[@]}"; do
            mkdir /tmp/chest_xray1_$client
            for stage in "${stages[@]}"; do
                mkdir /tmp/chest_xray1_$client/$stage
                for class in "${classes[@]}"; do
                    mkdir /tmp/chest_xray1_$client/$stage/$class
                done
            done
        done

        # Copy data to client folders
        i=0
        for file in $(find /tmp/chest_xray_new -name '*.jpeg'); do
            classnr=$(( i % 5 ))
            cp $file ${file/chest_xray_new/chest_xray1_${clients[classnr]}}
            i=$((i+1))
        done

        #Upload data assets
        az ml data create --workspace-name Asia-Hospital3 \
                          --name pneumonia-dataset3 \
                          --path /tmp/chest_xray1_asia \
                          --type uri_folder

        az ml data create --workspace-name Europe-Hospital3 \
                          --name pneumonia-dataset3 \
                          --path /tmp/chest_xray1_europe \
                          --type uri_folder

        az ml data create --workspace-name US-Hospital3 \
                          --name pneumonia-dataset3 \
                          --path /tmp/chest_xray1_us \
                          --type uri_folder
